//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photos_product
    {
        public int id_photo { get; set; }
        public int idProduct { get; set; }
        public string name { get; set; }
    
        public virtual product product { get; set; }
    }
}
